const styles = {
  container: {
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    padding: 24,
    maxWidth: 900,
    margin: "30px auto",
    background: "linear-gradient(135deg, #f0f4f8, #d9e2ec)",
    borderRadius: 12,
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.12)",
  },
  bigButton: {
    padding: "18px 48px",
    margin: 24,
    fontSize: 28,
    borderRadius: 50,
    cursor: "pointer",
    border: "none",
    background: "linear-gradient(45deg, #6a11cb, #2575fc)",
    color: "#fff",
    fontWeight: "600",
    boxShadow: "0 6px 20px rgba(101, 74, 233, 0.6)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },
  bigButtonHover: {
    transform: "scale(1.05)",
    boxShadow: "0 12px 28px rgba(101, 74, 233, 0.8)",
  },
  sectionTitle: {
    marginTop: 40,
    fontSize: 26,
    fontWeight: "700",
    color: "#222",
    textAlign: "center",
    letterSpacing: "0.03em",
  },
  roomList: {
    listStyleType: "none",
    padding: 0,
    marginTop: 20,
  },
  roomItem: {
    padding: "14px 20px",
    margin: "10px 0",
    borderRadius: 10,
    backgroundColor: "#fff",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: 18,
    color: "#333",
    transition: "background-color 0.3s ease, box-shadow 0.3s ease",
  },
  roomItemHover: {
    backgroundColor: "#2575fc",
    color: "#fff",
    boxShadow: "0 8px 20px rgba(37, 117, 252, 0.5)",
  },
  conversationBox: {
    borderRadius: 12,
    padding: 20,
    marginTop: 20,
    maxHeight: 340,
    overflowY: "auto",
    backgroundColor: "#fff",
    boxShadow: "0 4px 18px rgba(0,0,0,0.1)",
  },
  message: {
    padding: 12,
    margin: "8px 0",
    borderRadius: 12,
    background: "linear-gradient(135deg, #6a11cb, #2575fc)",
    color: "#fff",
    maxWidth: "75%",
    fontWeight: "500",
    fontSize: 16,
    boxShadow: "0 4px 12px rgba(101, 74, 233, 0.5)",
  },
  metadata: {
    fontSize: 12,
    color: "#666",
    padding: "6px 10px",
    borderRadius: 6,
    marginTop: 4,
    fontStyle: "italic",
  },
  inputArea: {
    marginTop: 20,
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },

  input: {
    flexGrow: 1,
    padding: "12px 16px",
    fontSize: 16,
    borderRadius: 12,
    border: "1.5px solid #ddd",
    outline: "none",
    boxSizing: "border-box",
  },

  sendButton: {
    padding: "12px 24px",
    fontSize: 16,
    borderRadius: 12,
    backgroundColor: "#2575fc",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 44,
  },

  homeButton: {
    padding: "12px 24px",
    fontSize: 16,
    borderRadius: 12,
    backgroundColor: "#6c757d",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 44,
  },
  homeButtonHover: {
    backgroundColor: "#333",
  },
  operatorLoginOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0,0,0,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  operatorLoginBox: {
    backgroundColor: "#fff",
    padding: 40,
    borderRadius: 16,
    boxShadow: "0 10px 30px rgba(0,0,0,0.25)",
    width: 360,
    display: "flex",
    flexDirection: "column",
  },
  operatorInput: {
    marginBottom: 20,
    padding: 14,
    fontSize: 17,
    borderRadius: 12,
    border: "1.5px solid #2575fc",
    outline: "none",
    transition: "border-color 0.3s ease",
  },
  operatorButton: {
    padding: "14px 32px",
    fontSize: 18,
    borderRadius: 12,
    background: "linear-gradient(45deg, #6a11cb, #2575fc)",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    fontWeight: "700",
    boxShadow: "0 6px 18px rgba(101, 74, 233, 0.7)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: 24,
    fontSize: 16,
  },
  th: {
    borderBottom: "2px solid #ddd",
    padding: 12,
    backgroundColor: "#f9f9f9",
    textAlign: "left",
    color: "#555",
  },
  td: {
    borderBottom: "1px solid #eee",
    padding: 12,
    color: "#444",
  },
  claimButton: {
    padding: "8px 16px",
    fontSize: 15,
    borderRadius: 10,
    backgroundColor: "#28a745",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    fontWeight: "600",
    boxShadow: "0 4px 14px rgba(40, 167, 69, 0.6)",
    transition: "background-color 0.3s ease",
  },
  claimButtonHover: {
    backgroundColor: "#218838",
  },
};

export default styles;
